export const POLISH = [
  //Snowed-In Collection
  {
    id: 0,
    title: "Snowed In Collection",
    desc: "",
    price: 62.5,
    img: require("./images/snowedin.jpg"),
    hover: require("./images/snowedin-hover.jpg"),
    rating: 5,
    reviews: 1,
    collection: "snowedin",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 1,
    title: "Bundled Up",
    desc: "",
    price: 10.0,
    img: require("./images/bundledup.jpg"),
    hover: require("./images/bundledup-hover.jpg"),
    rating: 5,
    reviews: 1,
    collection: "snowedin",
    holographic: true,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 2,
    title: "Tinsel",
    desc: "",
    price: 10.0,
    img: require("./images/tinsel.jpg"),
    hover: require("./images/tinsel-hover.jpg"),
    rating: 0,
    reviews: 0,
    collection: "snowedin",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 3,
    title: "Greatness",
    desc: "",
    price: 12.5,
    img: require("./images/greatness.jpg"),
    hover: require("./images/greatness-hover.jpg"),
    rating: 0,
    reviews: 0,
    collection: "snowedin",
    holographic: true,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 4,
    title: "Christmas Cookie",
    desc: "",
    price: 10.0,
    img: require("./images/christmascookie.jpg"),
    hover: require("./images/christmascookie-hover.jpg"),
    rating: 5,
    reviews: 2,
    collection: "snowedin",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 5,
    title: "Cold As Ice",
    desc: "",
    price: 10.0,
    img: require("./images/coldasice.jpg"),
    hover: require("./images/coldasice-hover.jpg"),
    rating: 5,
    reviews: 2,
    collection: "snowedin",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 6,
    title: "Say Love",
    desc: "",
    price: 60.0,
    img: require("./images/saylove.jpg"),
    hover: require("./images/saylove-hover.jpg"),
    rating: 5,
    reviews: 4,
    collection: "snowedin",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  //Monarchy Collection
  {
    id: 7,
    title: "Monarchy Collection",
    desc: "",
    price: 60.0,
    img: require("./images/monarchy.jpg"),
    hover: require("./images/monarchy-hover.jpg"),
    rating: 5,
    reviews: 14,
    collection: "monarchy",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 8,
    title: "Legacy",
    desc: "",
    price: 10.0,
    img: require("./images/legacy.jpg"),
    hover: require("./images/legacy-hover.jpg"),
    rating: 5,
    reviews: 21,
    collection: "monarchy",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: true
  },
  {
    id: 9,
    title: "Empress",
    desc: "",
    price: 10.0,
    img: require("./images/empress.jpg"),
    hover: require("./images/empress-hover.jpg"),
    rating: 5,
    reviews: 9,
    collection: "monarchy",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 10,
    title: "Isabella",
    desc: "",
    price: 10.0,
    img: require("./images/isabella.jpg"),
    hover: require("./images/isabella-hover.jpg"),
    rating: 5,
    reviews: 46,
    collection: "monarchy",
    holographic: true,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 11,
    title: "Bloodline",
    desc: "",
    price: 10.0,
    img: require("./images/bloodline.jpg"),
    hover: require("./images/bloodline-hover.jpg"),
    rating: 5,
    reviews: 35,
    collection: "monarchy",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 12,
    title: "Chateau",
    desc: "",
    price: 10.0,
    img: require("./images/chateau.jpg"),
    hover: require("./images/chateau-hover.jpg"),
    rating: 5,
    reviews: 42,
    collection: "monarchy",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: true
  },
  {
    id: 13,
    title: "Vanity",
    desc: "",
    price: 10.0,
    img: require("./images/vanity.jpg"),
    hover: require("./images/vanity-hover.jpg"),
    rating: 5,
    reviews: 47,
    collection: "monarchy",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  //Nine to Five Collection
  {
    id: 14,
    title: "Nine to Five Collection",
    desc: "",
    price: 70.0,
    img: require("./images/ninetofive.jpg"),
    hover: require("./images/ninetofive-hover.jpg"),
    rating: 5,
    reviews: 25,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  {
    id: 15,
    title: "Overcoat",
    desc: "",
    price: 10.0,
    img: require("./images/overcoat.jpg"),
    hover: require("./images/overcoat-hover.jpg"),
    rating: 5,
    reviews: 12,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  {
    id: 16,
    title: "ASAP",
    desc: "",
    price: 10.0,
    img: require("./images/asap.jpg"),
    hover: require("./images/asap-hover.jpg"),
    rating: 5,
    reviews: 29,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  {
    id: 17,
    title: "Coffee Run",
    desc: "",
    price: 10.0,
    img: require("./images/coffeerun.jpg"),
    hover: require("./images/coffeerun-hover.jpg"),
    rating: 5,
    reviews: 56,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  {
    id: 18,
    title: "Portfolio",
    desc: "",
    price: 10.0,
    img: require("./images/portfolio.jpg"),
    hover: require("./images/portfolio-hover.jpg"),
    rating: 5,
    reviews: 15,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  {
    id: 19,
    title: "Rumor Has It",
    desc: "",
    price: 10.0,
    img: require("./images/rumorhasit.jpg"),
    hover: require("./images/rumorhasit-hover.jpg"),
    rating: 5,
    reviews: 19,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  {
    id: 20,
    title: "CEO",
    desc: "",
    price: 10.0,
    img: require("./images/ceo.jpg"),
    hover: require("./images/ceo-hover.jpg"),
    rating: 5,
    reviews: 23,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  {
    id: 21,
    title: "Internship",
    desc: "",
    price: 10.0,
    img: require("./images/internship.jpg"),
    hover: require("./images/internship-hover.jpg"),
    rating: 5,
    reviews: 48,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  //Summer Feels Collection
  {
    id: 22,
    title: "Summer Feels Collection",
    desc: "",
    price: 67.5,
    img: require("./images/summerfeels.jpg"),
    hover: require("./images/summerfeels-hover.jpg"),
    rating: 5,
    reviews: 26,
    collection: "summerfeels",
    holographic: false,
    ultrachrome: true,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 23,
    title: "Summer Lovin'",
    desc: "",
    price: 12.5,
    img: require("./images/summerlovin.jpg"),
    hover: require("./images/summerlovin-hover.jpg"),
    rating: 5,
    reviews: 80,
    collection: "summerfeels",
    holographic: false,
    ultrachrome: true,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 24,
    title: "On Repeat",
    desc: "",
    price: 10.0,
    img: require("./images/onrepeat.jpg"),
    hover: require("./images/onrepeat-hover.jpg"),
    rating: 5,
    reviews: 38,
    collection: "summerfeels",
    holographic: false,
    ultrachrome: true,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 25,
    title: "Heat Wave",
    desc: "",
    price: 12.5,
    img: require("./images/heatwave.jpg"),
    hover: require("./images/heatwave-hover.jpg"),
    rating: 5,
    reviews: 48,
    collection: "summerfeels",
    holographic: false,
    ultrachrome: true,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 26,
    title: "Talk It Up",
    desc: "",
    price: 10.0,
    img: require("./images/talkitup.jpg"),
    hover: require("./images/talkitup-hover.jpg"),
    rating: 5,
    reviews: 57,
    collection: "summerfeels",
    holographic: false,
    ultrachrome: true,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 27,
    title: "Morning Rays",
    desc: "",
    price: 12.5,
    img: require("./images/morningrays.jpg"),
    hover: require("./images/morningrays-hover.jpg"),
    rating: 5,
    reviews: 45,
    collection: "summerfeels",
    holographic: false,
    ultrachrome: true,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 28,
    title: "Freefall",
    desc: "",
    price: 10.0,
    img: require("./images/freefall.jpg"),
    hover: require("./images/freefall-hover.jpg"),
    rating: 5,
    reviews: 35,
    collection: "summerfeels",
    holographic: false,
    ultrachrome: true,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  //New Years 2016 Collection
  {
    id: 29,
    title: "New Year's Collection 2016",
    desc: "",
    price: 60.0,
    img: require("./images/newyears2016.jpg"),
    hover: require("./images/newyears2016-hover.jpg"),
    rating: 5,
    reviews: 23,
    collection: "newyears2016",
    holographic: false,
    ultrachrome: false,
    ultrametallic: true,
    jelly: false,
    shimmer: false
  },
  {
    id: 30,
    title: "Velvet Rope",
    desc: "",
    price: 10.0,
    img: require("./images/velvetrope.jpg"),
    hover: require("./images/velvetrope-hover.jpg"),
    rating: 5,
    reviews: 69,
    collection: "newyears2016",
    holographic: false,
    ultrachrome: false,
    ultrametallic: true,
    jelly: false,
    shimmer: false
  },
  {
    id: 31,
    title: "Caesar",
    desc: "",
    price: 10.0,
    img: require("./images/caesar.jpg"),
    hover: require("./images/caesar-hover.jpg"),
    rating: 5,
    reviews: 85,
    collection: "newyears2016",
    holographic: false,
    ultrachrome: false,
    ultrametallic: true,
    jelly: false,
    shimmer: false
  },
  {
    id: 32,
    title: "Arctic Lights",
    desc: "",
    price: 10.0,
    img: require("./images/arcticlights.jpg"),
    hover: require("./images/arcticlights-hover.jpg"),
    rating: 5,
    reviews: 121,
    collection: "newyears2016",
    holographic: false,
    ultrachrome: false,
    ultrametallic: true,
    jelly: false,
    shimmer: false
  },
  {
    id: 33,
    title: "Madison Ave",
    desc: "",
    price: 10.0,
    img: require("./images/madisonave.jpg"),
    hover: require("./images/madisonave-hover.jpg"),
    rating: 5,
    reviews: 126,
    collection: "newyears2016",
    holographic: false,
    ultrachrome: false,
    ultrametallic: true,
    jelly: false,
    shimmer: false
  },
  {
    id: 34,
    title: "Copper Top",
    desc: "",
    price: 10.0,
    img: require("./images/coppertop.jpg"),
    hover: require("./images/coppertop-hover.jpg"),
    rating: 5,
    reviews: 110,
    collection: "newyears2016",
    holographic: false,
    ultrachrome: false,
    ultrametallic: true,
    jelly: false,
    shimmer: false
  },
  {
    id: 35,
    title: "Private Reserve",
    desc: "",
    price: 10.0,
    img: require("./images/privatereserve.jpg"),
    hover: require("./images/privatereserve-hover.jpg"),
    rating: 5,
    reviews: 131,
    collection: "newyears2016",
    holographic: false,
    ultrachrome: false,
    ultrametallic: true,
    jelly: false,
    shimmer: false
  }
];
