export const POLISH = [
  //Snowed-In Collection
  {
    id: 0,
    title: "Snowed In Collection",
    desc: "",
    price: 62.5,
    img: "https://i.imgur.com/JoaJ1iQ.jpg",
    hover: "https://i.imgur.com/Idjd6X3.jpg",
    rating: 5,
    reviews: 1,
    collection: "snowedin",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 1,
    title: "Bundled Up",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/RPTTK4g.jpg",
    hover: "https://i.imgur.com/CHGe7Zd.jpg",
    rating: 5,
    reviews: 1,
    collection: "snowedin",
    holographic: true,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 2,
    title: "Tinsel",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/9PI8uz1.jpg",
    hover: "https://i.imgur.com/yXhBG9F.jpg",
    rating: 0,
    reviews: 0,
    collection: "snowedin",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 3,
    title: "Greatness",
    desc: "",
    price: 12.5,
    img: "https://i.imgur.com/TpOutVI.jpg",
    hover: "https://i.imgur.com/kIE9R3m.jpg",
    rating: 0,
    reviews: 0,
    collection: "snowedin",
    holographic: true,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 4,
    title: "Christmas Cookie",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/55yynw5.jpg",
    hover: "https://i.imgur.com/D2zphFO.jpg",
    rating: 5,
    reviews: 2,
    collection: "snowedin",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 5,
    title: "Cold As Ice",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/z8cSXUx.jpg",
    hover: "https://i.imgur.com/EvLiLkz.jpg",
    rating: 5,
    reviews: 2,
    collection: "snowedin",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 6,
    title: "Say Love",
    desc: "",
    price: 60.0,
    img: "https://i.imgur.com/bKcjr4O.jpg",
    hover: "https://i.imgur.com/bKcjr4O.jpg",
    rating: 5,
    reviews: 4,
    collection: "snowedin",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  //Monarchy Collection
  {
    id: 7,
    title: "Monarchy Collection",
    desc: "",
    price: 60.0,
    img: "https://i.imgur.com/CPiPs0V.jpg",
    hover: "https://i.imgur.com/LcXAKyL.jpg",
    rating: 5,
    reviews: 14,
    collection: "monarchy",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 8,
    title: "Legacy",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/i8xlczk.jpg",
    hover: "https://i.imgur.com/i8xlczk.jpg",
    rating: 5,
    reviews: 21,
    collection: "monarchy",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: true
  },
  {
    id: 9,
    title: "Empress",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/QszXGjC.jpg",
    hover: "https://i.imgur.com/t0PJxNp.jpg",
    rating: 5,
    reviews: 9,
    collection: "monarchy",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 10,
    title: "Isabella",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/f4lmsft.jpg",
    hover: "https://i.imgur.com/8LX1YIz.jpg",
    rating: 5,
    reviews: 46,
    collection: "monarchy",
    holographic: true,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 11,
    title: "Bloodline",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/BaBctfG.jpg",
    hover: "https://i.imgur.com/2u6vPJE.jpg",
    rating: 5,
    reviews: 35,
    collection: "monarchy",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 12,
    title: "Chateau",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/3PI6vow.jpg",
    hover: "https://i.imgur.com/QxfAcxB.jpg",
    rating: 5,
    reviews: 42,
    collection: "monarchy",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: true
  },
  {
    id: 13,
    title: "Vanity",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/uwVH2X5.jpg",
    hover: "https://i.imgur.com/BctrBal.jpg",
    rating: 5,
    reviews: 47,
    collection: "monarchy",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  //Nine to Five Collection
  {
    id: 14,
    title: "Nine to Five Collection",
    desc: "",
    price: 70.0,
    img: "https://i.imgur.com/G9sxUNj.jpg",
    hover: "https://i.imgur.com/N6YmJ9g.jpg",
    rating: 5,
    reviews: 25,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  {
    id: 15,
    title: "Overcoat",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/ZpnmMN9.jpg",
    hover: "https://i.imgur.com/p9tnquq.jpg",
    rating: 5,
    reviews: 12,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  {
    id: 16,
    title: "ASAP",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/L5cEVGb.jpg",
    hover: "https://i.imgur.com/lKhzgOz.jpg",
    rating: 5,
    reviews: 29,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  {
    id: 17,
    title: "Coffee Run",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/q2mgW5d.jpg",
    hover: "https://i.imgur.com/kdxXGcM.jpg",
    rating: 5,
    reviews: 56,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  {
    id: 18,
    title: "Portfolio",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/zBxSuyR.jpg",
    hover: "https://i.imgur.com/Q9ncRQL.jpg",
    rating: 5,
    reviews: 15,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  {
    id: 19,
    title: "Rumor Has It",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/50b1Psz.jpg",
    hover: "https://i.imgur.com/aelcsHK.jpg",
    rating: 5,
    reviews: 19,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  {
    id: 20,
    title: "CEO",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/whvMKSr.jpg",
    hover: "https://i.imgur.com/AD5IE3a.jpg",
    rating: 5,
    reviews: 23,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  {
    id: 21,
    title: "Internship",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/hc2iOwL.jpg",
    hover: "https://i.imgur.com/LNXFW3S.jpg",
    rating: 5,
    reviews: 48,
    collection: "ninetofive",
    holographic: false,
    ultrachrome: false,
    ultrametallic: false,
    jelly: true,
    shimmer: false
  },
  //Summer Feels Collection
  {
    id: 22,
    title: "Summer Feels Collection",
    desc: "",
    price: 67.5,
    img: "https://i.imgur.com/6WWho9i.jpg",
    hover: "https://i.imgur.com/ZZQnbqH.jpg",
    rating: 5,
    reviews: 26,
    collection: "summerfeels",
    holographic: false,
    ultrachrome: true,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 23,
    title: "Summer Lovin'",
    desc: "",
    price: 12.5,
    img: "https://i.imgur.com/gecyOsw.jpg",
    hover: "https://i.imgur.com/nu3kXwz.jpg",
    rating: 5,
    reviews: 80,
    collection: "summerfeels",
    holographic: false,
    ultrachrome: true,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 24,
    title: "On Repeat",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/A7q7vHW.jpg",
    hover: "https://i.imgur.com/ZuCbJsD.jpg",
    rating: 5,
    reviews: 38,
    collection: "summerfeels",
    holographic: false,
    ultrachrome: true,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 25,
    title: "Heat Wave",
    desc: "",
    price: 12.5,
    img: "https://i.imgur.com/dFOrb9v.jpg",
    hover: "https://i.imgur.com/aFEXkA3.jpg",
    rating: 5,
    reviews: 48,
    collection: "summerfeels",
    holographic: false,
    ultrachrome: true,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 26,
    title: "Talk It Up",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/4zqlvAW.jpg",
    hover: "https://i.imgur.com/eiaLm9M.jpg",
    rating: 5,
    reviews: 57,
    collection: "summerfeels",
    holographic: false,
    ultrachrome: true,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 27,
    title: "Morning Rays",
    desc: "",
    price: 12.5,
    img: "https://i.imgur.com/tbJtD2P.jpg",
    hover: "https://i.imgur.com/aFEXkA3.jpg",
    rating: 5,
    reviews: 45,
    collection: "summerfeels",
    holographic: false,
    ultrachrome: true,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  {
    id: 28,
    title: "Freefall",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/BRgSqAJ.jpg",
    hover: "https://i.imgur.com/DtGXYUx.jpg",
    rating: 5,
    reviews: 35,
    collection: "summerfeels",
    holographic: false,
    ultrachrome: true,
    ultrametallic: false,
    jelly: false,
    shimmer: false
  },
  //New Years 2016 Collection
  {
    id: 29,
    title: "New Year's Collection 2016",
    desc: "",
    price: 60.0,
    img: "https://i.imgur.com/Adrxvrk.jpg",
    hover: "https://i.imgur.com/JWuNbV0.jpg",
    rating: 5,
    reviews: 23,
    collection: "newyears2016",
    holographic: false,
    ultrachrome: false,
    ultrametallic: true,
    jelly: false,
    shimmer: false
  },
  {
    id: 30,
    title: "Velvet Rope",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/Zsl5u5r.jpg",
    hover: "https://i.imgur.com/EUN9maF.jpg",
    rating: 5,
    reviews: 69,
    collection: "newyears2016",
    holographic: false,
    ultrachrome: false,
    ultrametallic: true,
    jelly: false,
    shimmer: false
  },
  {
    id: 31,
    title: "Caesar",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/VqgxD53.jpg",
    hover: "https://i.imgur.com/sA1Iy7h.jpg",
    rating: 5,
    reviews: 85,
    collection: "newyears2016",
    holographic: false,
    ultrachrome: false,
    ultrametallic: true,
    jelly: false,
    shimmer: false
  },
  {
    id: 32,
    title: "Arctic Lights",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/pQxdCj8.jpg",
    hover: "https://i.imgur.com/rsgA1Hv.jpg",
    rating: 5,
    reviews: 121,
    collection: "newyears2016",
    holographic: false,
    ultrachrome: false,
    ultrametallic: true,
    jelly: false,
    shimmer: false
  },
  {
    id: 33,
    title: "Madison Ave",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/a7UX7NN.jpg",
    hover: "https://i.imgur.com/jh8FDa4.jpg",
    rating: 5,
    reviews: 126,
    collection: "newyears2016",
    holographic: false,
    ultrachrome: false,
    ultrametallic: true,
    jelly: false,
    shimmer: false
  },
  {
    id: 34,
    title: "Copper Top",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/xLVMA5O.jpg",
    hover: "https://i.imgur.com/fxkklms.jpg",
    rating: 5,
    reviews: 110,
    collection: "newyears2016",
    holographic: false,
    ultrachrome: false,
    ultrametallic: true,
    jelly: false,
    shimmer: false
  },
  {
    id: 35,
    title: "Private Reserve",
    desc: "",
    price: 10.0,
    img: "https://i.imgur.com/RVPGXDf.jpg",
    hover: "https://i.imgur.com/8kiRjPn.jpg",
    rating: 5,
    reviews: 131,
    collection: "newyears2016",
    holographic: false,
    ultrachrome: false,
    ultrametallic: true,
    jelly: false,
    shimmer: false
  }
];
